# Generated by Django 5.0.6 on 2024-07-30 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employees_permissions',
            field=models.ManyToManyField(through='api.EmployeePermissions', to='api.permission'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_permissions', models.ManyToManyField(related_name='required_by_positions', to='api.permission')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='workable_positions',
            field=models.ManyToManyField(related_name='employees', to='api.position'),
        ),
        migrations.CreateModel(
            name='PositionEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='history',
            field=models.ManyToManyField(related_name='positions', through='api.PositionEmployees', to='api.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_history',
            field=models.ManyToManyField(related_name='employees', through='api.PositionEmployees', to='api.employee'),
        ),
    ]
