# Generated by Django 5.0.6 on 2025-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_employees_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='required_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='required_by_positions', to='api.permission'),
        ),
    ]
