# Generated by Django 5.0.6 on 2025-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_position_required_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
