# Generated by Django 5.0.6 on 2025-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employee_comments_permission_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionemployees',
            name='present_employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='present_employees', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
