# Generated by Django 5.0.6 on 2025-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_positionemployees_present_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionemployees',
            name='present_employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
