# Generated by Django 5.0.6 on 2025-06-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_positionemployees_present_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionemployees',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
