# Generated by Django 5.0.6 on 2025-06-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_positionemployees_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionemployees',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
